#! /bin/sh

# ======== BSPWM CONFIG ============================
# Inspired by:
# -- https://github.com/notusknot/dotfiles
# -- https://gitlab.com/protesilaos/dotfiles

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start picom
picom &

# Wallpaper
feh --bg-fill --randomize ~/Pictures/wallpapers/* &

# Workspace setup
# --> adapted from https://protesilaos.com/codelog/multihead-bspwm-polybar/
if [ -x $HOME/.config/bspwm/bspwm_dual_monitor_setup ];then
    bspwm_dual_monitor_setup
fi
bspc monitor eDP -d 1 2 3 4 5 6 7 8 9
bspc monitor 'HDMI-A-0' -d A B C D E

# Start polybar
if [ -x /usr/bin/polybar ]; then
    bash $HOME/.config/polybar/launch.sh
fi

# Window styling
bspc config border_width         5
bspc config normal_border_color  "#555555"
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
