#! /bin/sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start picom
picom &

# Start polybar
~/.config/polybar/launch.sh &

feh --bg-fill --randomize ~/Pictures/wallpapers/* &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
