#! /bin/sh

# ======== BSPWM CONFIG ============================
# Inspired by: https://github.com/notusknot/dotfiles

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start picom
picom &

# Start polybar
~/.config/polybar/launch.sh &

# Wallpaper
feh --bg-fill --randomize ~/Pictures/wallpapers/* &

# Workspace names
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Window styling
bspc config border_width         5
bspc config normal_border_color  "#555555"
bspc config window_gap           10
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
