#!/bin/bash

# Detect if external monitor is connected, then tell xrandr about it and set them up properly
# --> adapted from https://protesilaos.com/codelog/multihead-bspwm-polybar/
external_monitor=$(xrandr --query | grep 'HDMI-A-0')
if [[ $external_monitor = *connected* ]]; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 2560x1080 --rotate normal --right-of eDP
fi

