#!/usr/bin/env bash
set -Eeuo pipefail # https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail

# ------------------------------------------------------------------------------
# --- Create a new recipe ------------------------------------------------------
# ------------------------------------------------------------------------------

echo "Enter a title for your recipe:"
read -p "(title) " title
CURRENT_TIME=$(date '+%FT%T')
FILENAME=$HOME/Documents/local-notes/recipes/$(echo $title | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed 's/[A-Z]/\L&/g').md
if [ ! -f "$FILENAME" ]; then
  touch "$FILENAME"
  TMPL="---\ncreated: \"$CURRENT_TIME\"\nmodified: \"$CURRENT_TIME\"\ntitle: \"$title\"\ntags:\n  - \"recipe\"\n---\n\n\`\`\`{ingredients}\n\`\`\`\n"
  echo -en "$TMPL" > $FILENAME
fi
nvim "$FILENAME"
