
[font]
size = 8.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "Full"
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 8
y = 13

[general]
import = [
    # "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
    # "~/.config/alacritty/themes/themes/ashes_light.toml"
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]
