import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[font]
size = 8.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "Full"
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
