import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[font]
size = 10.0

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[window]
decorations = "Full"
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
