# [colors.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"

# [colors.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#9699a8"
# yellow = "#e0af68"

# [colors.primary]
# background = "#24283b"
# foreground = "#a9b1d6"

# [schemes.atom_one_light.bright]
# black = "0x000000"
# blue = "0x2f5af3"
# cyan = "0x3e953a"
# green = "0x3e953a"
# magenta = "0xa00095"
# red = "0xde3d35"
# white = "0xffffff"
# yellow = "0xd2b67b"

# [schemes.atom_one_light.normal]
# black = "0x000000"
# blue = "0x2f5af3"
# cyan = "0x3e953a"
# green = "0x3e953a"
# magenta = "0xa00095"
# red = "0xde3d35"
# white = "0xbbbbbb"
# yellow = "0xd2b67b"

# [schemes.atom_one_light.primary]
# background = "0xf8f8f8"
# foreground = "0x2a2b33"

# [schemes.nord.bright]
# black = "0x4C566A"
# blue = "0x81A1C1"
# cyan = "0x8FBCBB"
# green = "0xA3BE8C"
# magenta = "0xB48EAD"
# red = "0xBF616A"
# white = "0xECEFF4"
# yellow = "0xEBCB8B"

# [schemes.nord.normal]
# black = "0x3B4252"
# blue = "0x81A1C1"
# cyan = "0x88C0D0"
# green = "0xA3BE8C"
# magenta = "0xB48EAD"
# red = "0xBF616A"
# white = "0xE5E9F0"
# yellow = "0xEBCB8B"

# [schemes.nord.primary]
# background = "0x2E3440"
# foreground = "0xD8DEE9"

# [schemes.nova.bright]
# black = "#899BA6"
# blue = "#83AFE5"
# cyan = "#7FC1CA"
# green = "#A8CE93"
# magenta = "#D18EC2"
# red = "#F2C38F"
# white = "#E6EEF3"
# yellow = "#DADA93"

# [schemes.nova.cursor]
# cursor = "#C0C5CE"
# text = "#212121"

# [schemes.nova.normal]
# black = "#3C4C55"
# blue = "#83AFE5"
# cyan = "#7FC1CA"
# green = "#A8CE93"
# magenta = "#9A93E1"
# red = "#DF8C8C"
# white = "#C5D4DD"
# yellow = "#DADA93"

# [schemes.nova.primary]
# background = "#3C4C55"
# foreground = "#C5D4DD"

# [schemes.tokyo-night.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"

# [schemes.tokyo-night.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#787c99"
# yellow = "#e0af68"

# [schemes.tokyo-night.primary]
# background = "#1a1b26"
# foreground = "#a9b1d6"

# [schemes.tokyo-night-storm.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"

# [schemes.tokyo-night-storm.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#9699a8"
# yellow = "#e0af68"

# [schemes.tokyo-night-storm.primary]
# background = "#24283b"
# foreground = "#a9b1d6"

import = [
    "~/.config/alacritty/themes/themes/nightfox.toml"
]

[font]
size = 10.0

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"


[window]
decorations = "Full"
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
