
[font]
size = 8.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "Full"
# opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 4
y = 8

[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
    # "~/.config/alacritty/themes/themes/papertheme.toml"
    # "~/.config/alacritty/themes/themes/ashes_light.toml"
    # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
    # "~/.config/alacritty/themes/themes/citylights.toml"
    # "~/.config/alacritty/themes/themes/falcon.toml"
    # "~/.config/alacritty/themes/themes/ayu_dark.toml"
    # "~/.config/alacritty/themes/themes/tender.toml"
]
